### ISSUE TITLE
Unable install and build on Windows 10

### ISSUE THREAD

**Issue by trrahul** [Richasy/FantasyCopilot#29]
### Bug description

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
  Source=Microsoft.Windows.AppLifecycle.Projection
  StackTrace:
   at WinRT.ActivationFactory`1.As(Guid iid)
   at Microsoft.Windows.AppLifecycle.AppInstance.Make___objRef_global__Microsoft_Windows_AppLifecycle_IAppInstanceStatics()
   at Microsoft.Windows.AppLifecycle.AppInstance.get__objRef_global__Microsoft_Windows_AppLifecycle_IAppInstanceStatics()
   at Microsoft.Windows.AppLifecycle.AppInstance.FindOrRegisterForKey(String key)
   at FantasyCopilot.App.Program.Main(String[] args) in C:\Users\Rahul\Source\Repos\FantasyCopilot\src\App\Program.cs:line 22

  This exception was originally thrown at this call stack:
    System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(int)
    WinRT.BaseActivationFactory.BaseActivationFactory(string, string)

Inner Exception 1:
COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))

### Reproduce steps

```plain text
1. Clone repo and open in visual studio
2. Select Unpackaged build target
3. Run
```

### Expected behavior

1. App should install
2. Souce should build

### Screenshot

![image](https://github.com/Richasy/FantasyCopilot/assets/7353840/fac324ba-9b9d-4eb4-8765-0d80f40db2e6)
![image](https://github.com/Richasy/FantasyCopilot/assets/7353840/6ec4c2cb-f6a3-4456-943a-dfeb40f8fc0f)

### Application source

- [X] Microsoft Store
- [X] Github
- [ ] Others

### System version

- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Others

### Other system versions

19045

**Comment by trrahul** [comment]
Adding `<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>` bypasses this error and leads to another. 

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Exception of type 'System.InvalidOperationException' was thrown.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.Storage.IApplicationDataStaticsMethods.get_Current(IObjectReference _obj)
   at Windows.Storage.ApplicationData.get_Current()
   at FantasyCopilot.Toolkits.SettingsToolkit.ReadLocalSetting[T](SettingNames settingName, T defaultValue) in C:\Users\Rahul\Source\Repos\FantasyCopilot\src\Toolkits\Toolkits.Desktop\SettingsToolkit.cs:line 20
   at FantasyCopilot.App.App.GetSavedWindowPosition() in C:\Users\Rahul\Source\Repos\FantasyCopilot\src\App\App.xaml.cs:line 113
   at FantasyCopilot.App.App.MoveAndResize() in C:\Users\Rahul\Source\Repos\FantasyCopilot\src\App\App.xaml.cs:line 161
   at FantasyCopilot.App.App.LaunchWindow() in C:\Users\Rahul\Source\Repos\FantasyCopilot\src\App\App.xaml.cs:line 142
   at FantasyCopilot.App.App.OnLaunched(LaunchActivatedEventArgs args) in C:\Users\Rahul\Source\Repos\FantasyCopilot\src\App\App.xaml.cs:line 82
   at Microsoft.UI.Xaml.Application.Microsoft.UI.Xaml.IApplicationOverrides.OnLaunched(LaunchActivatedEventArgs args)
   at ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(IntPtr thisPtr, IntPtr args)
```

**Comment by Richasy** [comment]
Sorry, but this app is only support win11 right now.

**Comment by trrahul** [comment]
Any plans to support windows 10?

**Comment by Richasy** [comment]
There are currently no plans to support Win10 in the short term. However, combining AI applications with Win11 in the future can enable us to do some really cool things.
